/**
 * Progressive Web App layer: manifest and service worker.
 *
 * This is what makes the site installable, work offline, and be packageable
 * for the stores — via Trusted Web Activity on Google Play, and as the web
 * layer inside a Capacitor shell on iOS. See docs/09-app-store-strategy.md
 * for what each store additionally requires.
 *
 * Both artefacts are generated rather than hand-maintained so the deploy base
 * path (or a future custom domain) stays a single config change.
 */

/** The web app manifest, as a JSON string. */
export function manifest(site) {
  const base = site.basePath || "";
  const scope = base + "/";
  return JSON.stringify({
    name: `${site.brand} — ${site.descriptor}`,
    short_name: site.brand,
    description: site.positioning,
    id: scope,
    start_url: scope,
    scope,
    display: "standalone",
    orientation: "portrait-primary",
    background_color: "#FCFAF7",
    theme_color: "#1D4E45",
    lang: site.locale,
    dir: "ltr",
    categories: ["travel", "lifestyle"],
    icons: [
      { src: `${base}/assets/icons/icon-192.png`, sizes: "192x192", type: "image/png", purpose: "any" },
      { src: `${base}/assets/icons/icon-512.png`, sizes: "512x512", type: "image/png", purpose: "any" },
      { src: `${base}/assets/icons/maskable-192.png`, sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: `${base}/assets/icons/maskable-512.png`, sizes: "512x512", type: "image/png", purpose: "maskable" }
    ],
    shortcuts: [
      { name: "Plan a trip", url: `${base}/plan/` },
      { name: "Women & Travel", url: `${base}/women-and-travel/` },
      { name: "Search", url: `${base}/search/` }
    ]
  }, null, 2);
}

/**
 * The service worker.
 *
 * @param {object} site
 * @param {string[]} precache  root-relative URLs to cache on install
 * @param {string} version     cache-busting build stamp
 */
export function serviceWorker(site, precache, version) {
  const base = site.basePath || "";
  const urls = precache.map(u => base + u);
  return `/* Pehchan service worker — generated by src/build.mjs. Do not edit. */
const VERSION = ${JSON.stringify(version)};
const CACHE = "pehchan-" + VERSION;
const OFFLINE = ${JSON.stringify(base + "/offline.html")};
const PRECACHE = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    const c = await caches.open(CACHE);
    // Individually, so one 404 cannot fail the whole install.
    await Promise.all(PRECACHE.map(u => c.add(u).catch(() => {})));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (e) => {
  if (e.data === "skip-waiting") self.skipWaiting();
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  // Never touch other origins (Google Forms, analytics): let the network own them.
  if (url.origin !== self.location.origin) return;

  // Pages: network first, so content stays fresh; fall back to cache, then
  // to the offline page.
  if (req.mode === "navigate") {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const c = await caches.open(CACHE);
        c.put(req, fresh.clone());
        return fresh;
      } catch {
        return (await caches.match(req)) || (await caches.match(OFFLINE)) || Response.error();
      }
    })());
    return;
  }

  // Static assets: stale-while-revalidate.
  e.respondWith((async () => {
    const cached = await caches.match(req);
    const network = fetch(req).then(res => {
      if (res && res.status === 200 && res.type === "basic") {
        caches.open(CACHE).then(c => c.put(req, res.clone()));
      }
      return res;
    }).catch(() => null);
    return cached || (await network) || Response.error();
  })());
});
`;
}

/** Minimal standalone offline page — must not depend on anything uncached. */
export function offlinePage(site) {
  const base = site.basePath || "";
  return `<!doctype html>
<html lang="${site.locale}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Offline — ${site.brand}</title>
<meta name="theme-color" content="#1D4E45">
<style>
  :root { color-scheme: light dark; }
  body { margin:0; min-height:100vh; display:grid; place-items:center; padding:24px;
         background:#FCFAF7; color:#191411;
         font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; }
  @media (prefers-color-scheme: dark) { body { background:#121110; color:#F2EDE6; } }
  .box { max-width:32rem; text-align:center; }
  h1 { font-family:Georgia,"Times New Roman",serif; font-weight:400; font-size:1.75rem; margin:0 0 .5rem; }
  p { margin:0 0 1.5rem; line-height:1.6; opacity:.8; }
  a { display:inline-block; padding:.75rem 1.5rem; border-radius:999px;
      background:#1D4E45; color:#FBF9F6; text-decoration:none; }
</style>
</head>
<body>
  <div class="box">
    <h1>You are offline</h1>
    <p>This page has not been saved to your device yet. Pages you have already
       visited are still available — reconnect to load anything new.</p>
    <a href="${base}/">Go to the homepage</a>
  </div>
</body>
</html>
`;
}
