/* Pehchan service worker — generated by src/build.mjs. Do not edit. */
const VERSION = "3b39e248174b";
const CACHE = "pehchan-" + VERSION;
const OFFLINE = "/pehchanthetraveller19.github.io/offline.html";
const PRECACHE = [
  "/pehchanthetraveller19.github.io/",
  "/pehchanthetraveller19.github.io/offline.html",
  "/pehchanthetraveller19.github.io/assets/css/main.css",
  "/pehchanthetraveller19.github.io/assets/css/tokens.css",
  "/pehchanthetraveller19.github.io/assets/js/site.js",
  "/pehchanthetraveller19.github.io/assets/favicon.svg",
  "/pehchanthetraveller19.github.io/assets/icons/icon-192.png",
  "/pehchanthetraveller19.github.io/assets/icons/icon-512.png"
];

self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    const c = await caches.open(CACHE);
    // Individually, so one 404 cannot fail the whole install.
    await Promise.all(PRECACHE.map(u => c.add(u).catch(() => {})));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (e) => {
  if (e.data === "skip-waiting") self.skipWaiting();
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  // Never touch other origins (Google Forms, analytics): let the network own them.
  if (url.origin !== self.location.origin) return;

  // Pages: network first, so content stays fresh; fall back to cache, then
  // to the offline page.
  if (req.mode === "navigate") {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const c = await caches.open(CACHE);
        c.put(req, fresh.clone());
        return fresh;
      } catch {
        return (await caches.match(req)) || (await caches.match(OFFLINE)) || Response.error();
      }
    })());
    return;
  }

  // Static assets: stale-while-revalidate.
  e.respondWith((async () => {
    const cached = await caches.match(req);
    const network = fetch(req).then(res => {
      if (res && res.status === 200 && res.type === "basic") {
        caches.open(CACHE).then(c => c.put(req, res.clone()));
      }
      return res;
    }).catch(() => null);
    return cached || (await network) || Response.error();
  })());
});
